
image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CONTAINER_REGISTRY_HOST: registry.gitlab.com
  CONTAINER_TEST_IMAGE: $CONTAINER_REGISTRY_HOST/$CI_PROJECT_PATH:$CI_BUILD_REF
  CONTAINER_RELEASE_IMAGE: $CONTAINER_REGISTRY_HOST/$CI_PROJECT_PATH:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CONTAINER_REGISTRY_HOST

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE --build-arg NPM_TOKEN="$NPM_TOKEN" .
    - docker push $CONTAINER_TEST_IMAGE
  except:
    - tags

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - echo "Not implemented yet"
    #- docker run $CONTAINER_TEST_IMAGE /script/to/run/tests

release-image:latest:
  dependencies: []
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

release-image:tags:
  dependencies: []
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
    - docker push $CONTAINER_REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
  only:
    - tags
