sudo: required

language: bash
services: docker

env:
 - DOCKER_IMAGE=docker-test-frontend-server

script:
  - docker build -t ${DOCKER_IMAGE} .

after_script:
  - docker images
  - docker run -d -p 8080:8888 -t ${DOCKER_IMAGE}
  - docker ps -a
